server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: sector-service
          uri: lb://sector-service
          predicates:
            - Path=/sectors/**
        - id: class-service
          uri: lb://class-service
          predicates:
            - Path=/classes/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
