server:
  port: 8081

spring:
  application:
    name: sector-service

  datasource:
    url: jdbc:postgresql://localhost:5432/sector_db
    username: postgres
    password: passer
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
