# Configuration du port HTTP pour ce microservice
server:
  port: 8082  # Le service sera accessible via http://localhost:8082

# Configuration Spring générale
spring:
  application:
    name: class-service  # Nom du microservice, utilisé pour l'enregistrement Eureka

  # Configuration de la base de données PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/class_db  # URL de connexion à la base PostgreSQL (nom de la BDD : class_db)
    username: postgres  # Nom d'utilisateur PostgreSQL
    password: passer    # Mot de passe associé

  # Configuration JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update  # Hibernate met à jour automatiquement le schéma à partir des entités (à éviter en prod)
    show-sql: true       # Affiche les requêtes SQL exécutées dans la console (utile pour le debug)

# Configuration du client Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # URL du serveur Eureka 

# Configuration de Feign Client
feign:
  client:
    config:
      default:
        loggerLevel: basic
