server:
  port: 8082

spring:
  application:
    name: class-service

  datasource:
    url: jdbc:postgresql://localhost:5432/class_db
    username: postgres
    password: passer
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# Active Feign clients
feign:
  client:
    config:
      default:
        loggerLevel: basic
